CREATE TABLE TBL_COMPUTER(
	COMPUTERID UNIQUEIDENTIFIER NOT NULL,
	COMPUTERNUMBER INT NOT NULL,
	SPECIFICATION NVARCHAR(MAX) NULL,
	ISACTIVE BIT NOT NULL,
	CREATEDDATE DATETIME NOT NULL,
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL,
	CONSTRAINT PK_TBL_COMPUTER_COMPUTERID PRIMARY KEY NONCLUSTERED(
		COMPUTERID ASC
	)ON [PRIMARY],
	CONSTRAINT UQ_TBL_COMPUTER_COMPUTERNUMBER UNIQUE CLUSTERED(
		COMPUTERNUMBER ASC
	)ON [PRIMARY]
)ON [PRIMARY]

ALTER TABLE TBL_COMPUTER ADD CONSTRAINT DF_TBL_COMPUTER_COMPUTERID DEFAULT (NEWID()) FOR COMPUTERID
ALTER TABLE TBL_COMPUTER ADD CONSTRAINT DF_TBL_COMPUTER_CREATEDDATE DEFAULT (GETDATE()) FOR CREATEDDATE