CREATE TABLE TBL_COURSEANDSECTION(
	COURSESECTIONID UNIQUEIDENTIFIER NOT NULL,
	COURSE NVARCHAR(50) NOT NULL,
	SECTION NVARCHAR(50) NOT NULL,
	ISACTIVE BIT NULL,

	CONSTRAINT PK_TBL_COURSEANDSECTION_COURSESECTIONID PRIMARY KEY NONCLUSTERED(
		COURSESECTIONID ASC
	)ON [PRIMARY],
	CONSTRAINT UQ_TBL_COURSEANDSECTION_COURSE_SECTION UNIQUE CLUSTERED(
		COURSE ASC,
		SECTION ASC
	)ON [PRIMARY]
)ON [PRIMARY]

ALTER TABLE TBL_COURSEANDSECTION ADD CONSTRAINT DF_TBL_COURSEANDSECTION DEFAULT (NEWID()) FOR COURSESECTIONID


CREATE TABLE TBL_NAMES(
	NAMEID UNIQUEIDENTIFIER NOT NULL,
	FIRSTNAME NVARCHAR(50) NOT NULL,
	MIDDLENAME NVARCHAR(50) NOT NULL,
	LASTNAME NVARCHAR(50) NOT NULL,
	COURSESECTIONID UNIQUEIDENTIFIER NOT NULL,

	CREATEDDATE DATETIME NOT NULL,
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL,
	CONSTRAINT PK_TBL_NAMES_NAMEID PRIMARY KEY NONCLUSTERED(
		NAMEID ASC
	)ON [PRIMARY],
	CONSTRAINT UQ_TBL_NAMES_FIRSTNAME_MIDDLENAME_LASTNAME UNIQUE CLUSTERED(
		FIRSTNAME ASC,
		MIDDLENAME ASC,
		LASTNAME ASC
	)ON [PRIMARY]
)ON [PRIMARY]

ALTER TABLE TBL_NAMES ADD CONSTRAINT DF_TBL_NAMES_NAMEID DEFAULT (NEWID()) FOR NAMEID
ALTER TABLE TBL_NAMES ADD CONSTRAINT DF_TBL_NAMES_CREATEDDATE DEFAULT (GETDATE()) FOR CREATEDDATE
ALTER TABLE TBL_NAMES ADD CONSTRAINT FK_TBL_NAMES_COURSESECTIONID FOREIGN KEY (COURSESECTIONID) REFERENCES TBL_COURSEANDSECTION (COURSESECTIONID)
