//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccessSystemDBEntities : DbContext
    {
        public AccessSystemDBEntities()
            : base("name=AccessSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_ADMINUSER> TBL_ADMINUSER { get; set; }
        public DbSet<TBL_COURSEANDSECTION> TBL_COURSEANDSECTION { get; set; }
        public DbSet<TBL_NAMES> TBL_NAMES { get; set; }
        public DbSet<TBL_COMPUTER> TBL_COMPUTER { get; set; }
        public DbSet<TBL_LOG> TBL_LOG { get; set; }
    }
}
