//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COURSEANDSECTION
    {
        public TBL_COURSEANDSECTION()
        {
            this.TBL_NAMES = new HashSet<TBL_NAMES>();
        }
    
        public System.Guid COURSESECTIONID { get; set; }
        public string COURSE { get; set; }
        public string SECTION { get; set; }
        public bool ISACTIVE { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public string YEAR { get; set; }
    
        public virtual ICollection<TBL_NAMES> TBL_NAMES { get; set; }
    }
}
