//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NAMES
    {
        public TBL_NAMES()
        {
            this.TBL_LOG = new HashSet<TBL_LOG>();
        }
    
        public System.Guid NAMEID { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string LASTNAME { get; set; }
        public System.Guid COURSESECTIONID { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public string RFIDCODE { get; set; }
    
        public virtual TBL_COURSEANDSECTION TBL_COURSEANDSECTION { get; set; }
        public virtual ICollection<TBL_LOG> TBL_LOG { get; set; }
    }
}
