//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COMPUTER
    {
        public TBL_COMPUTER()
        {
            this.TBL_LOG = new HashSet<TBL_LOG>();
        }
    
        public System.Guid COMPUTERID { get; set; }
        public int COMPUTERNUMBER { get; set; }
        public string SPECIFICATION { get; set; }
        public bool ISACTIVE { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
    
        public virtual ICollection<TBL_LOG> TBL_LOG { get; set; }
    }
}
