//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOG
    {
        public System.Guid LOGID { get; set; }
        public System.Guid NAMEID { get; set; }
        public System.Guid COMPUTERID { get; set; }
        public System.DateTime STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
    
        public virtual TBL_COMPUTER TBL_COMPUTER { get; set; }
        public virtual TBL_NAMES TBL_NAMES { get; set; }
    }
}
